### PR TITLE
Native async

### PR DESCRIPTION
**Pull request by sejoker**
- uprade jest, eslint, babel, webpack to the latest version
-  target browsers with 1% of global usage (no IE 11)
- use native async/await support in browsers without polyfill
- should address https://github.com/cloudflare/Cloudflare-WordPress/issues/399

### CODE REVIEW

**Review by xtuc — APPROVED** [review]

**Review by jacobbednarz — APPROVED** [review]
This looks fine to me however I'll also ping a couple of folks with more front end knowledge than myself to ensure there aren't any dragons hiding here.

**Comment by manatarms** [comment]
Lets validate this with a full frontend build locally before we deploy

**Review by manatarms — APPROVED** [review]

**Comment by sejoker** [comment]
@jacobbednarz it would be great to include the change in the next plugin release.

**Comment by jacobbednarz** [comment]
can do; totally blanked on this for the 4.5.0 release

**Pull request merged**
