### PR TITLE
Jwineman/react155

### PR DESCRIPTION
**Pull request by jwineman**
There are warnings from `react-select` which `cf-component-select` depends on.  Being tracked here:
https://github.com/JedWatson/react-select/pull/1658

I'll PR again when they patch.

### CODE REVIEW

**Comment by thellimist** [comment]
This is relevant https://github.com/yahoo/react-intl/pull/918

**Comment by jwineman** [comment]
Ah I'd forgotten about that, I'm watching that issue as well.  I'd like to merge now if thats okay. The warnings don't show up in production bundles and there is no break in functionality.

**Comment by thellimist** [comment]
We can merge once we finish the task completely. There's no urgency

**Comment by jwineman** [comment]
I want to avoid a rebase.

**Comment by jwineman** [comment]
Merging per our conversation

**Pull request merged**
