### PR TITLE
Release v2.8.1

### PR DESCRIPTION
**Pull request by manatarms**

### CODE REVIEW

**Comment by thellimist** [comment]
Could you rewrite the commit history so `Release v2.9.0` commit does not show up. For normal commits it's fine but it creates confusion in release commits.

**Comment by manatarms** [comment]
Lol my bad. Pushed the wrong commit

**Comment by thellimist** [comment]
I'm not sure if github is bugged or the commit has `2.9.0` rather than `2.8.1`.

**Comment by thellimist** [comment]
Ohh the commit id is wrong. n/m

**Comment by manatarms** [comment]
Okay all good.

**Pull request merged**
